services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://api.gustavocastro.app}
        - VITE_APP_NAME=${VITE_APP_NAME:-"Dash App"}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-"1.0.0"}
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
